"""Protocol package for framework adapters and canonical trajectory contracts."""

from mobile_world.runtime.protocol.adapter import (
    TERMINAL_ACTION_TYPES,
    AdapterArtifactsResult,
    AdapterFinalizeInput,
    AdapterFinalizeResult,
    AdapterInitializeInput,
    AdapterInitializeResult,
    AdapterProfile,
    AdapterStepInput,
    AdapterStepResult,
    ArtifactRecord,
    FrameworkAdapter,
    LegacyAgentAdapter,
    is_terminal_action,
)
from mobile_world.runtime.protocol.capability_policy import (
    CapabilityDecision,
    CapabilityPolicyConfig,
    CapabilityPolicyRule,
    resolve_capability_policy,
)
from mobile_world.runtime.protocol.conformance import (
    run_conformance_suite,
    validate_evaluator_audit,
    validate_metrics_summary,
    validate_task_artifacts,
)
from mobile_world.runtime.protocol.evaluator import (
    BaseEvaluator,
    ConsistencyCheck,
    EvaluationAudit,
    EvaluatorInput,
    EvaluatorResult,
    EvidenceReference,
    TaskNativeEvaluator,
    TrajectoryJudgeConfig,
    TrajectoryJudgeVerdict,
    clear_evaluators,
    create_evaluator,
    get_evaluator_factory,
    list_evaluators,
    register_evaluator,
)
from mobile_world.runtime.protocol.events import (
    CANONICAL_TRAJECTORY_SCHEMA_VERSION,
    CanonicalMetricsEvent,
    CanonicalScoreEvent,
    CanonicalStepEvent,
    CanonicalTrajectoryHeader,
    MetricsQualityFlags,
)
from mobile_world.runtime.protocol.metrics import MetricsCollector
from mobile_world.runtime.protocol.registry import (
    AdapterRegistration,
    clear_adapters,
    get_adapter_registration,
    has_adapter,
    list_adapters,
    list_registrations,
    register_adapter,
)
from mobile_world.runtime.protocol.reporting import (
    TaskRunRecord,
    aggregate_framework_runs,
    load_task_run_records,
    write_report,
)
from mobile_world.runtime.protocol.reproducibility import evaluate_reproducibility
from mobile_world.runtime.protocol.tool_router import (
    NormalizedToolError,
    ToolDispatchResult,
    UnifiedToolRouter,
    classify_action_type,
)
from mobile_world.runtime.protocol.trace_converter import (
    LEGACY_TRAJECTORY_SCHEMA_VERSION,
    TRACE_CONVERTER_VERSION,
    convert_legacy_directory,
    convert_legacy_trajectory,
)
from mobile_world.runtime.protocol.validation import (
    ProtocolValidationError,
    ValidationIssue,
    ValidationReport,
    run_protocol_preflight,
    validate_adapter_contracts,
    validate_canonical_schema,
)

__all__ = [
    "AdapterArtifactsResult",
    "AdapterFinalizeInput",
    "AdapterFinalizeResult",
    "AdapterInitializeInput",
    "AdapterInitializeResult",
    "AdapterProfile",
    "AdapterRegistration",
    "AdapterStepInput",
    "AdapterStepResult",
    "ArtifactRecord",
    "BaseEvaluator",
    "CANONICAL_TRAJECTORY_SCHEMA_VERSION",
    "CanonicalMetricsEvent",
    "CapabilityDecision",
    "CapabilityPolicyConfig",
    "CapabilityPolicyRule",
    "ConsistencyCheck",
    "CanonicalScoreEvent",
    "CanonicalStepEvent",
    "CanonicalTrajectoryHeader",
    "EvaluationAudit",
    "EvaluatorInput",
    "EvaluatorResult",
    "EvidenceReference",
    "FrameworkAdapter",
    "LEGACY_TRAJECTORY_SCHEMA_VERSION",
    "TRACE_CONVERTER_VERSION",
    "TERMINAL_ACTION_TYPES",
    "is_terminal_action",
    "LegacyAgentAdapter",
    "MetricsQualityFlags",
    "MetricsCollector",
    "NormalizedToolError",
    "ProtocolValidationError",
    "TaskNativeEvaluator",
    "TaskRunRecord",
    "ToolDispatchResult",
    "TrajectoryJudgeConfig",
    "TrajectoryJudgeVerdict",
    "UnifiedToolRouter",
    "ValidationIssue",
    "ValidationReport",
    "clear_evaluators",
    "create_evaluator",
    "clear_adapters",
    "classify_action_type",
    "get_evaluator_factory",
    "get_adapter_registration",
    "has_adapter",
    "load_task_run_records",
    "list_adapters",
    "list_evaluators",
    "list_registrations",
    "register_evaluator",
    "register_adapter",
    "resolve_capability_policy",
    "run_protocol_preflight",
    "run_conformance_suite",
    "validate_evaluator_audit",
    "validate_metrics_summary",
    "validate_task_artifacts",
    "validate_adapter_contracts",
    "validate_canonical_schema",
    "convert_legacy_trajectory",
    "convert_legacy_directory",
    "aggregate_framework_runs",
    "write_report",
    "evaluate_reproducibility",
]
